name: "hasura-sample-app"

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

user-env:
  PG_DATABASE_URL:
    description: "Postgres database URL"
    mandatory: true
  HASURA_GRAPHQL_JWT_SECRET:
    default: "{\"key\": \"this-is-the-hasura-nextjs-secret-key-replace-it-with-something-secure\",\"type\": \"HS256\"}"
    description: "JWT Secret key"
    mandatory: true
