name: "hasura-sample-app"

static-ennnv:
  STREAMING_SUBSCRIPTION_FLAG: true

user-env:
  PG_DATABASE_URL:
    description: "Postgres database URL"
    mandatory: true
  ACTION_WEBHOOK_URL:
    default: "http://localhost:3000"
    description: "Action webhook url"
    mandatory: true
  HASURA_GRAPHQL_JWT_SECRET:
    default: "{\"key\": \"this-is-the-hasura-nextjs-secret-key-replace-it-with-something-secure\",\"type\": \"HS256\"}"
    description: "JWT Secret key"
    mandatory: true
